module.exports = [
  {
    id: 'rima',
    name: 'リマ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'miyako',
    name: 'ミヤコ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kuuka',
    name: 'クウカ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'jun',
    name: 'ジュン',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kuuka-ohedo',
    name: 'クウカ(オーエド)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kaori',
    name: 'カオリ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'saren-xmas',
    name: 'サレン(クリスマス)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'tsumugi-halloween',
    name: 'ツムギ(ハロウィン)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'rei-new-year',
    name: 'レイ(ニューイヤー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'rin-deremas',
    name: 'リン(デレマス)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'pecorine',
    name: 'ペコリーヌ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'pecorine-princess',
    name: 'ペコリーヌ(プリンセス)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'ruka',
    name: 'ルカ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kokkoro-new-year',
    name: 'コッコロ(ニューイヤー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'nozomi',
    name: 'ノゾミ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'muimi',
    name: 'ムイミ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'makoto',
    name: 'マコト',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kaya',
    name: 'カヤ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'hiyori-new-year',
    name: 'ヒヨリ(ニューイヤー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'ninon-ohedo',
    name: 'ニノン(オーエド)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'akino',
    name: 'アキノ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'makoto-summer',
    name: 'マコト(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'jun-summer',
    name: 'ジュン(サマー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'matsuri',
    name: 'マツリ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kuroe',
    name: 'クロエ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'matsuri-halloween',
    name: 'マツリ(ハロウィン)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'eriko-valentine',
    name: 'エリコ(バレンタイン)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'akino-xmas',
    name: 'アキノ(クリスマス)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'ayane-xmas',
    name: 'アヤネ(クリスマス)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'ruka-summer',
    name: 'ルカ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'tsumugi',
    name: 'ツムギ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'inori',
    name: 'イノリ',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'hiyori',
    name: 'ヒヨリ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'misogi',
    name: 'ミソギ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'ayane',
    name: 'アヤネ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'misogi-halloween',
    name: 'ミソギ(ハロウィン)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'tamaki',
    name: 'タマキ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'tomo',
    name: 'トモ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'tieru',
    name: 'チエル',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'tamaki-summer',
    name: 'タマキ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'eriko',
    name: 'エリコ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'pecorine-summer',
    name: 'ペコリーヌ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kurumi',
    name: 'クルミ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'djeeta',
    name: 'ジータ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'rei',
    name: 'レイ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'iriya-xmas',
    name: 'イリヤ(クリスマス)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'anna-summer',
    name: 'アンナ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'christina-xmas',
    name: 'クリスティーナ(クリスマス)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'sizuru',
    name: 'シズル',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'christina',
    name: 'クリスティーナ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kurumi-xmas',
    name: 'クルミ(クリスマス)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'mimi',
    name: 'ミミ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'sinobu',
    name: 'シノブ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'mimi-halloween',
    name: 'ミミ(ハロウィン)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'uzuki-deremas',
    name: 'ウズキ(デレマス)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'rei-halloween',
    name: 'レイ(ハロウィン)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'sizuru-valentine',
    name: 'シズル(バレンタイン)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'mahiru-ranger',
    name: 'マヒル(レンジャー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'mahiru',
    name: 'マヒル',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'tomo-magical',
    name: 'トモ(マジカル)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'yukari',
    name: 'ユカリ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'yukari-xmas',
    name: 'ユカリ(クリスマス)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'monika',
    name: 'モニカ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'ninon',
    name: 'ニノン',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'nozomi-xmas',
    name: 'ノゾミ(クリスマス)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'mifuyu',
    name: 'ミフユ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'rin-ranger',
    name: 'リン(レンジャー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'iriya',
    name: 'イリヤ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kaori-summer',
    name: 'カオリ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'saren',
    name: 'サレン',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'anna',
    name: 'アンナ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'sinobu-halloween',
    name: 'シノブ(ハロウィン)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'mifuyu-summer',
    name: 'ミフユ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kokkoro',
    name: 'コッコロ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'ayumi-wonder',
    name: 'アユミ(ワンダー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'ayumi',
    name: 'アユミ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'grea',
    name: 'グレア',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'monika-magical',
    name: 'モニカ(マジカル)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'akari-angel',
    name: 'アカリ(エンジェル)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'yori-angel',
    name: 'ヨリ(エンジェル)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'kokkoro-summer',
    name: 'コッコロ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'remu',
    name: 'レム',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'ramu',
    name: 'ラム',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'rin',
    name: 'リン',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kokkoro-princess',
    name: 'コッコロ(プリンセス)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'labyrista',
    name: 'ラビリスタ',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'mitsuki',
    name: 'ミツキ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'akari',
    name: 'アカリ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'yori',
    name: 'ヨリ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'saren-summer',
    name: 'サレン(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'miyako-halloween',
    name: 'ミヤコ(ハロウィン)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'arisa',
    name: 'アリサ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'anne',
    name: 'アン',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'ruu',
    name: 'ルゥ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'neneka',
    name: 'ネネカ',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'aoi-student',
    name: 'アオイ(編入生)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kyaru-new-year',
    name: 'キャル(ニューイヤー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'mio-deremas',
    name: 'ミオ(デレマス)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'rino',
    name: 'リノ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'suzuna',
    name: 'スズナ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'suzuna-summer',
    name: 'スズナ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'siori',
    name: 'シオリ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'siori-magical',
    name: 'シオリ(マジカル)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'io',
    name: 'イオ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'io-summer',
    name: 'イオ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'suzume',
    name: 'スズメ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'suzume-new-year',
    name: 'スズメ(ニューイヤー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'emiria',
    name: 'エミリア',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kasumi',
    name: 'カスミ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kasumi-magical',
    name: 'カスミ(マジカル)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'rino-wonder',
    name: 'リノ(ワンダー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'misato',
    name: 'ミサト',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'nanaka',
    name: 'ナナカ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'yui-new-year',
    name: 'ユイ(ニューイヤー)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'kyaru',
    name: 'キャル',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'hatsune',
    name: 'ハツネ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'misaki',
    name: 'ミサキ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'luna',
    name: 'ルナ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'yui-princess',
    name: 'ユイ(プリンセス)',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'chika-xmas',
    name: 'チカ(クリスマス)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'suzume-summer',
    name: 'スズメ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kyaru-summer',
    name: 'キャル(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'aoi',
    name: 'アオイ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'chika',
    name: 'チカ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'maho-summer',
    name: 'マホ(サマー)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'maho',
    name: 'マホ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'yui',
    name: 'ユイ',
    maxStar: 6,
    hasSpecialEquipment: true,
  },
  {
    id: 'yuki',
    name: 'ユキ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'yuni',
    name: 'ユニ',
    maxStar: 5,
    hasSpecialEquipment: false,
  },
  {
    id: 'kyouka',
    name: 'キョウカ',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'misaki-halloween',
    name: 'ミサキ(ハロウィン)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
  {
    id: 'kyouka-halloween',
    name: 'キョウカ(ハロウィン)',
    maxStar: 5,
    hasSpecialEquipment: true,
  },
]
